'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import BottomNav from '@/components/BottomNav'
import { supabase } from '@/lib/supabase'
import { normalizeProfile, profileLocation, countryFlag, Profile } from '@/lib/profile'

export default function Matches() {
  const [matches, setMatches] = useState<{ id: string; profile: Profile }[]>([]); const [status, setStatus] = useState('Loading your matches...')
  useEffect(() => { (async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return setStatus('Sign in to see your matches.'); const { data: rows, error } = await supabase.from('matches').select('id,user1,user2,created_at').or(`user1.eq.${auth.user.id},user2.eq.${auth.user.id}`).order('created_at', { ascending: false }); if (error) return setStatus(error.message); const otherIds = (rows || []).map(row => row.user1 === auth.user.id ? row.user2 : row.user1); if (!otherIds.length) return setStatus(''); const { data: profiles } = await supabase.from('profiles').select('*').in('id', otherIds); const hydrated = await Promise.all((rows || []).map(async row => { const otherId = row.user1 === auth.user.id ? row.user2 : row.user1; const profile = (profiles || []).find(item => item.id === otherId); if (!profile) return null; let { data: conversation } = await supabase.from('conversations').select('id').eq('match_id', row.id).maybeSingle(); if (!conversation) conversation = (await supabase.from('conversations').insert({ match_id: row.id, user1: row.user1, user2: row.user2 }).select('id').single()).data; return conversation ? { id: conversation.id, profile: normalizeProfile(profile) } : null })); setMatches(hydrated.filter(Boolean) as { id: string; profile: Profile }[]); setStatus('') })() }, [])
  return <div className="app-shell"><header className="topbar"><div><p className="eyebrow">Your people</p><h1 className="display text-2xl font-bold mt-1">Matches</h1></div><Link href="/explore" className="icon-button" aria-label="Explore worldwide">🌍</Link></header><main className="content animate-page">{status && <p className="py-10 text-center text-sm text-stone-500">{status}</p>}{!status && !matches.length && <div className="soft-panel mt-5 bg-gradient-to-br from-violet-50 to-rose-50 text-center"><div className="text-5xl">🌍</div><h2 className="display mt-4 text-2xl font-bold">Your next match could be anywhere</h2><p className="mt-2 text-sm leading-5 text-stone-500">Explore worldwide discovery and meet people beyond your usual circle.</p><Link href="/discover" className="primary-button mt-5 inline-block">Discover worldwide</Link></div>}{matches.length > 0 && <><div className="mb-4 mt-5 flex items-center justify-between"><p className="eyebrow text-violet-600">Your matches</p><span className="text-xs text-stone-500">{matches.length} connections</span></div>{matches.map(match => <Link href={`/chat/${match.id}`} key={match.id} className="soft-panel mb-3 flex items-center gap-3 no-underline transition-transform hover:-translate-y-1"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-full bg-gradient-to-br from-violet-200 to-rose-200 font-bold text-violet-700">{match.profile.photos[0] ? <img src={match.profile.photos[0]} alt={match.profile.name} className="h-full w-full object-cover" /> : match.profile.name.slice(0, 1)}</div><div className="min-w-0"><p className="font-bold">{match.profile.name}</p><p className="truncate text-xs text-stone-500">{countryFlag(match.profile.country)} {profileLocation(match.profile)}</p></div><span className="ml-auto text-violet-600">→</span></Link>)}</>}</main><BottomNav /></div>
}
