'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'

export default function Chat() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [msgs, setMsgs] = useState<any[]>([]); const [txt, setTxt] = useState(''); const [userId, setUserId] = useState(''); const [otherId, setOtherId] = useState(''); const [status, setStatus] = useState('Loading conversation...')
  useEffect(() => { let channel: any; (async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return router.push('/auth'); setUserId(auth.user.id); const { data: match } = await supabase.from('matches').select('user1,user2').eq('id', id).maybeSingle(); if (!match) return setStatus('This conversation is unavailable.'); const other = match.user1 === auth.user.id ? match.user2 : match.user1; setOtherId(other); const { data, error } = await supabase.from('messages').select('*').or(`and(sender_id.eq.${auth.user.id},receiver_id.eq.${other}),and(sender_id.eq.${other},receiver_id.eq.${auth.user.id})`).order('created_at'); if (error) setStatus(error.message); else { setMsgs(data || []); setStatus('') } channel = supabase.channel(`messages-${id}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages' }, payload => { if ((payload.new as any).sender_id === other || (payload.new as any).receiver_id === other) setMsgs(current => [...current, payload.new]) }).subscribe() })(); return () => { if (channel) supabase.removeChannel(channel) } }, [id, router])
  const send = async () => { if (!txt.trim() || !userId || !otherId) return; const { data, error } = await supabase.from('messages').insert({ sender_id: userId, receiver_id: otherId, text: txt.trim() }).select().single(); if (error) setStatus(error.message); else { setMsgs(current => [...current, data]); setTxt('') } }
  return <div className="app-shell"><header className="topbar"><button className="icon-button" onClick={() => router.back()} aria-label="Go back">←</button><div><p className="font-bold">Messages</p><p className="text-xs text-stone-500">A private KLA Meet conversation</p></div><button className="icon-button" aria-label="Conversation safety">⋯</button></header><main className="content min-h-[calc(100vh-154px)]"><div className="soft-panel mt-4 mb-4 bg-gradient-to-r from-violet-50 to-rose-50 text-center"><p className="text-sm font-semibold">Start with curiosity</p><p className="mt-1 text-xs text-stone-500">Never send money or financial information to someone you just met.</p></div>{status && <p className="py-8 text-center text-xs text-stone-500">{status}</p>}<div className="space-y-3">{msgs.map((msg: any) => <div key={msg.id} className={`max-w-[80%] rounded-2xl p-3 ${msg.sender_id === userId ? 'ml-auto bg-violet-600 text-white' : 'border border-[#ece9e2] bg-white'}`}><p>{msg.text || msg.content}</p><p className="mt-1 text-[10px] opacity-55">{msg.created_at ? new Date(msg.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : ''}</p></div>)}</div></main><div className="fixed bottom-0 left-1/2 flex w-full max-w-[520px] -translate-x-1/2 gap-2 border-t border-[#ece9e2] bg-white p-3"><input value={txt} onChange={e => setTxt(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') send() }} placeholder="Write a message..." className="field rounded-full" /><button onClick={send} className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-gradient-to-r from-violet-600 to-pink-500 font-bold text-white" aria-label="Send message">↑</button></div></div>
}
