'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import BottomNav from '@/components/BottomNav'
import { supabase } from '@/lib/supabase'
import { COUNTRIES, countryFlag } from '@/lib/countries'

export default function ProfileEditor() {
  const router = useRouter(); const [userId, setUserId] = useState(''); const [form, setForm] = useState({ name: '', age: '', country: '', city: '', bio: '', intention: '', occupation: '', languages: '', interests: '' }); const [status, setStatus] = useState('')
  useEffect(() => { supabase.auth.getUser().then(async ({ data }) => { if (!data.user) return router.push('/auth'); setUserId(data.user.id); const { data: profile } = await supabase.from('profiles').select('*').eq('id', data.user.id).maybeSingle(); if (profile) setForm({ name: profile.full_name || profile.name || '', age: profile.age || '', country: profile.country_code || '', city: profile.city || profile.location || '', bio: profile.bio || '', intention: profile.relationship_intention || '', occupation: profile.occupation || '', languages: (profile.languages || []).join(', '), interests: (profile.interests || []).join(', ') }) }) }, [router])
  const update = (key: string, value: string) => setForm(current => ({ ...current, [key]: value })); const save = async () => { setStatus('Saving...'); const { error } = await supabase.from('profiles').upsert({ id: userId, full_name: form.name, name: form.name, age: Number(form.age), country_code: form.country, city: form.city, bio: form.bio, relationship_intention: form.intention, occupation: form.occupation, languages: form.languages.split(',').map(v => v.trim()).filter(Boolean), interests: form.interests.split(',').map(v => v.trim()).filter(Boolean), last_seen_at: new Date().toISOString() }); setStatus(error ? error.message : 'Profile saved') }
  return <div className="app-shell"><header className="topbar"><div><p className="eyebrow">Your identity</p><h1 className="display text-2xl font-bold mt-1">Edit profile</h1></div><div className="h-10 w-10 rounded-full bg-gradient-to-br from-[#7c3aed] to-[#fb7185] grid place-items-center text-white">✦</div></header><main className="content animate-page"><section className="soft-panel mt-3 bg-gradient-to-br from-white to-[#f6f1ff]"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-violet-600">PROFILE COMPLETE</p><p className="mt-1 text-sm text-stone-500">Complete your profile to get better matches.</p></div><strong className="display text-2xl">40%</strong></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-stone-200"><div className="h-full w-[40%] rounded-full bg-gradient-to-r from-[#7c3aed] to-[#fb7185]" /></div></section><section className="soft-panel mt-4 space-y-3"><div className="grid grid-cols-2 gap-3"><input className="field" value={form.name} onChange={e => update('name', e.target.value)} placeholder="Display name" /><input className="field" value={form.age} onChange={e => update('age', e.target.value)} placeholder="Age (18+)" type="number" min="18" /></div><select className="field" value={form.country} onChange={e => update('country', e.target.value)}><option value="">Choose country</option>{COUNTRIES.map(([code, name]) => <option key={code} value={code}>{countryFlag(code)} {name}</option>)}</select><input className="field" value={form.city} onChange={e => update('city', e.target.value)} placeholder="City" /><textarea className="field min-h-28" value={form.bio} onChange={e => update('bio', e.target.value)} placeholder="Tell the world something real about you" /><select className="field" value={form.intention} onChange={e => update('intention', e.target.value)}><option value="">Relationship intention</option><option>Serious relationship</option><option>New friends</option><option>Travel connection</option><option>Marriage</option></select><input className="field" value={form.languages} onChange={e => update('languages', e.target.value)} placeholder="Languages, separated by commas" /><input className="field" value={form.interests} onChange={e => update('interests', e.target.value)} placeholder="Interests, separated by commas" /><input className="field" value={form.occupation} onChange={e => update('occupation', e.target.value)} placeholder="Occupation" /><button onClick={save} className="primary-button w-full">Save profile</button>{status && <p className="text-center text-xs text-stone-500">{status}</p>}</section></main><BottomNav /></div>
}
