'use client'

import { useEffect, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import BottomNav from '@/components/BottomNav'
import { supabase } from '@/lib/supabase'
import { normalizeProfile, profileLocation, countryFlag, compatibility, Profile } from '@/lib/profile'

export default function ProfileView() {
  const params = useSearchParams(); const [profile, setProfile] = useState<Profile | null>(null); const [status, setStatus] = useState('Loading profile...')
  useEffect(() => { const id = params.get('id'); if (!id) return setStatus('Profile not found'); supabase.from('profiles').select('*').eq('id', id).maybeSingle().then(({ data, error }) => { if (error || !data) setStatus('Profile not found'); else { setProfile(normalizeProfile(data)); setStatus('') } }) }, [params])
  if (!profile) return <div className="app-shell"><main className="content pt-20 text-center"><p className="text-stone-500">{status}</p></main><BottomNav /></div>
  return <div className="app-shell"><header className="topbar"><button className="icon-button" onClick={() => history.back()} aria-label="Go back">←</button><p className="font-bold">Profile</p><button className="icon-button" aria-label="More options">⋯</button></header><main className="content animate-page"><div className="overflow-hidden rounded-[28px] bg-white shadow-xl"><div className="h-[390px] bg-gradient-to-br from-violet-200 to-rose-200">{profile.photos[0] ? <img src={profile.photos[0]} alt={profile.name} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-7xl font-bold text-violet-300">{profile.name.slice(0, 1)}</div>}</div><div className="p-5"><div className="flex items-start justify-between"><div><h1 className="display text-3xl font-bold">{profile.name}{profile.age ? `, ${profile.age}` : ''}</h1><p className="mt-1 text-sm text-stone-500">{countryFlag(profile.country)} {profileLocation(profile)}</p></div><div className="rounded-2xl bg-violet-50 px-3 py-2 text-center"><strong className="block text-xl text-violet-700">{compatibility(profile, {})}%</strong><span className="text-[10px] font-bold text-violet-500">MATCH</span></div></div><div className="mt-4 flex flex-wrap gap-2 text-xs">{profile.isOnline && <span className="rounded-full bg-emerald-50 px-3 py-2 text-emerald-700">● Online</span>}{profile.isVerified && <span className="rounded-full bg-sky-50 px-3 py-2 text-sky-700">✓ Verified</span>}{profile.intention && <span className="rounded-full bg-rose-50 px-3 py-2 text-rose-700">♥ {profile.intention}</span>}</div>{profile.bio && <p className="mt-6 leading-6 text-stone-600">{profile.bio}</p>}<div className="mt-6"><p className="eyebrow">Interests</p><div className="chip-row mt-2">{profile.interests.length ? profile.interests.map(item => <span className="rounded-full bg-violet-50 px-3 py-2 text-xs font-medium text-violet-700" key={item}>{item}</span>) : <span className="text-sm text-stone-500">No interests added yet</span>}</div></div><div className="mt-6"><p className="eyebrow">Why you match</p><div className="mt-3 grid grid-cols-2 gap-2">{['♥ Relationship goals', '🌍 Location', '🗣 Languages', '✨ Lifestyle'].map(item => <div className="rounded-xl bg-[#f8f6ff] p-3 text-xs font-medium" key={item}>{item}</div>)}</div></div><button onClick={async () => { const { data: user } = await supabase.auth.getUser(); if (user.user) await supabase.from('likes').insert({ from_id: user.user.id, to_id: profile.id }); setStatus('Like sent') }} className="primary-button mt-7 w-full">♥ Like {profile.name}</button>{status === 'Like sent' && <p className="mt-3 text-center text-xs text-emerald-600">Your interest was sent.</p>}</div></div></main><BottomNav /></div>
}
