'use client'

import Link from 'next/link'
import { Profile, compatibility, countryFlag, profileLocation } from '@/lib/profile'

export default function ProfileCard({ profile, onAction, compact = false }: { profile: Profile; onAction?: (type: string) => void; compact?: boolean }) {
  const score = compatibility(profile, {})
  return <article className={`profile-card ${compact ? 'h-[300px] min-h-0' : ''}`}><Link href={`/profile?id=${encodeURIComponent(profile.id)}`} className="block h-full"><div className="h-full w-full bg-gradient-to-br from-violet-100 via-rose-100 to-orange-100">{profile.photos[0] ? <img src={profile.photos[0]} alt={profile.name} /> : <div className="grid h-full place-items-center text-6xl font-bold text-violet-300">{profile.name.slice(0, 1).toUpperCase()}</div>}</div><div className="profile-info"><div className="mb-2 flex items-center gap-2"><span className="rounded-full bg-white/20 px-2 py-1 text-xs font-bold">{score}% Match</span>{profile.isOnline && <span className="text-xs text-emerald-300">● Online</span>}</div><h2>{profile.name}{profile.age ? `, ${profile.age}` : ''} {profile.isVerified && <span className="text-sky-300">✓</span>}</h2><p>{countryFlag(profile.country)} {profileLocation(profile)}</p>{profile.bio && <p className="line-clamp-2">{profile.bio}</p>}<div className="chip-row">{profile.interests.slice(0, 3).map(interest => <span className="chip" key={interest}>{interest}</span>)}</div></div></Link>{onAction && <div className="absolute bottom-5 right-5 z-10 flex gap-2"><button onClick={e => { e.preventDefault(); onAction('pass') }} className="grid h-10 w-10 place-items-center rounded-full bg-white/90 text-sm text-stone-700 shadow-lg" aria-label={`Pass on ${profile.name}`}>✕</button><button onClick={e => { e.preventDefault(); onAction('like') }} className="grid h-10 w-10 place-items-center rounded-full bg-[#fb7185] text-lg text-white shadow-lg" aria-label={`Like ${profile.name}`}>♥</button></div>}</article>
}
