'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import { Profile, compatibility, countryFlag, profileLocation } from '@/lib/profile'

export default function ProfileCard({ profile, onAction, compact = false }: { profile: Profile; onAction?: (type: string) => void; compact?: boolean }) {
  const score = compatibility(profile, {})
  return <motion.article className={`profile-card ${compact ? 'h-[300px] min-h-0' : ''}`} whileDrag={{ scale: 0.97 }} transition={{ type: 'spring', stiffness: 300, damping: 24 }}><Link href={`/profile?id=${encodeURIComponent(profile.id)}`} className="block h-full"><div className="h-full w-full bg-[#f3ead0]">{profile.photos[0] ? <img src={profile.photos[0]} alt={profile.name} /> : <div className="grid h-full place-items-center text-6xl font-bold text-[#c49b16]">{profile.name.slice(0, 1).toUpperCase()}</div>}</div><div className="profile-info"><div className="mb-2 flex items-center gap-2"><span className="rounded-full bg-white/20 px-2 py-1 text-xs font-bold">{score}% Match</span>{profile.isOnline && <span className="text-xs text-[#ffc629]">● Online</span>}</div><h2>{profile.name}{profile.age ? `, ${profile.age}` : ''} {profile.isVerified && <span className="text-[#ffc629]">✓</span>}</h2><p>{countryFlag(profile.country)} {profileLocation(profile)}</p>{profile.bio && <p className="line-clamp-2">{profile.bio}</p>}<div className="chip-row">{profile.interests.slice(0, 3).map(interest => <span className="chip" key={interest}>{interest}</span>)}</div></div></Link>{onAction && <div className="absolute bottom-5 right-5 z-10 flex gap-2"><motion.button whileTap={{ scale: 0.95 }} whileHover={{ scale: 1.02 }} onClick={e => { e.preventDefault(); onAction('pass') }} className="grid h-10 w-10 place-items-center rounded-full bg-white/90 text-sm text-stone-700 shadow-lg" aria-label={`Pass on ${profile.name}`}>✕</motion.button><motion.button whileTap={{ scale: 0.95 }} whileHover={{ scale: 1.02 }} onClick={e => { e.preventDefault(); onAction('like') }} className="grid h-10 w-10 place-items-center rounded-full bg-[#ffc629] text-lg text-[#242424] shadow-lg" aria-label={`Like ${profile.name}`}>♥</motion.button></div>}</motion.article>
}
