export function onboarding(step=1){
const s=parseInt(step)
const pages=[
`<div><h1 class="font-black text-[20px]">Enable Location</h1><p class="text-[12px] text-zinc-600 mt-2">Required to activate account</p><div class="mt-8 text-[64px] text-center">📍</div><button id="locBtn" class="mt-8 w-full bg-[#FFC700] py-3 rounded-full font-black border-2 border-black">Allow Location</button><p id="locStatus" class="text-[11px] mt-2 text-center"></p></div>`,
`<div><div class="text-[11px] font-bold">Step 2 of 6</div><h2 class="font-black text-[18px] mt-2">Bio & Age</h2><input id="bio" placeholder="Bio" class="w-full border-2 border-black rounded-xl p-3 mt-3 text-[13px]"/><input id="age" type="number" placeholder="Age" class="w-full border-2 border-black rounded-xl p-3 mt-2 text-[13px]"/><select id="gender" class="w-full border-2 border-black rounded-xl p-3 mt-2 text-[13px]"><option value="">Gender</option><option>Male</option><option>Female</option><option>Other</option></select><button onclick="save2()" class="mt-4 w-full bg-[#FFC700] py-3 rounded-full font-black border-2 border-black">Continue</button></div>`,
`<div><div class="text-[11px] font-bold">Step 3 of 6</div><h2 class="font-black text-[18px] mt-2">Add Photos</h2><input id="pics" type="file" multiple accept="image/*" class="mt-3 w-full"/><div id="preview" class="grid grid-cols-3 gap-2 mt-3"></div><button onclick="save3()" class="mt-4 w-full bg-[#FFC700] py-3 rounded-full font-black border-2 border-black">Continue</button></div>`,
`<div><div class="text-[11px] font-bold">Step 4 of 6</div><h2 class="font-black text-[18px] mt-2">Interests</h2><div id="intList" class="grid grid-cols-2 gap-2 mt-3 text-[12px] font-bold"><button class="int border-2 border-black rounded-full py-2" data-v="Music">Music</button><button class="int border-2 border-black rounded-full py-2" data-v="Travel">Travel</button><button class="int border-2 border-black rounded-full py-2" data-v="Foodie">Foodie</button><button class="int border-2 border-black rounded-full py-2" data-v="Fitness">Fitness</button></div><button onclick="save4()" class="mt-4 w-full bg-[#FFC700] py-3 rounded-full font-black border-2 border-black">Continue</button></div>`,
`<div><div class="text-[11px] font-bold">Step 5 of 6</div><h2 class="font-black text-[18px] mt-2">KYC (Optional)</h2><p class="text-[12px]">For blue tick verification</p><input type="file" class="mt-3 w-full border-2 border-dashed border-black rounded-xl p-4"/><div class="flex gap-2 mt-4"><button onclick="location.href='/signup/?step=6'" class="flex-1 border-2 border-black rounded-full py-3 font-bold text-[12px]">Skip</button><button onclick="save5()" class="flex-1 bg-[#FFC700] border-2 border-black rounded-full py-3 font-black text-[12px]">Submit</button></div></div>`,
`<div class="text-center"><h2 class="font-black text-[20px]">Activated! 🎉</h2><p class="text-[12px] mt-2">Location, Bio, Pics, Gender, Interests done</p><a href="/premium/" class="mt-4 block bg-[#FFC700] border-2 border-black py-3 rounded-full font-black text-[12px]">Go Premium 20K via PesaPal</a><div class="mt-3 grid grid-cols-2 gap-2"><a href="/discover/" class="border-2 border-black rounded-full py-2 font-black text-[12px]">Discover</a><a href="/near/" class="border-2 border-black bg-black text-white rounded-full py-2 font-black text-[12px]">Near</a></div></div>`
]
setTimeout(()=>{
 const b=document.getElementById('locBtn')
 if(b) b.onclick=()=>navigator.geolocation.getCurrentPosition(p=>{localStorage.setItem('kla_location_ok','1');location.href='/signup/?step=2'},()=>{document.getElementById('locStatus').innerText='Allow location to continue'})
 document.querySelectorAll('.int').forEach(x=>x.onclick=()=>x.classList.toggle('bg-[#FFC700]'))
 window.save2=()=>{ const d=JSON.parse(localStorage.getItem('kla_profile')||'{}'); d.bio=document.getElementById('bio').value; d.age=document.getElementById('age').value; d.gender=document.getElementById('gender').value; if(!d.bio||!d.age||!d.gender) return alert('Fill all'); localStorage.setItem('kla_profile',JSON.stringify(d)); location.href='/signup/?step=3'}
 window.save3=()=>{ const d=JSON.parse(localStorage.getItem('kla_profile')||'{}'); d.pics='yes'; localStorage.setItem('kla_profile',JSON.stringify(d)); location.href='/signup/?step=4'}
 window.save4=()=>{ const sel=[...document.querySelectorAll('.int.bg-\\[\\#FFC700\\]')].map(e=>e.dataset.v); if(!sel.length) return alert('Pick interests'); const d=JSON.parse(localStorage.getItem('kla_profile')||'{}'); d.interests=sel; localStorage.setItem('kla_profile',JSON.stringify(d)); location.href='/signup/?step=5'}
 window.save5=()=>{ const d=JSON.parse(localStorage.getItem('kla_profile')||'{}'); d.kyc='pending'; localStorage.setItem('kla_profile',JSON.stringify(d)); location.href='/signup/?step=6'}
},100)
return `<div class="min-h-screen bg-zinc-100 grid place-items-center p-4"><div class="bg-white w-[360px] rounded-[28px] p-6 border-[3px] border-black">${pages[s-1]}<div class="flex justify-center gap-1 mt-6">${[1,2,3,4,5,6].map(i=>`<div class="h-2 rounded-full ${i===s?'bg-[#FFC700] w-6':'bg-zinc-300 w-2'}"></div>`).join('')}</div></div></div>`
}
JScat > src/pages/discover.js <<'JS'
export function discover(){return `<div class="p-6"><header class="flex justify-between"><a href="/" class="font-black">KLA-MEET</a><div class="flex gap-2"><a href="/near/" class="px-4 py-2 rounded-full border-2 border-black text-[11px] font-bold">Near</a><a href="/chat/" class="px-4 py-2 rounded-full bg-[#FFC700] border-2 border-black text-[11px] font-black">Chat</a></div></header><h1 class="mt-6 font-black text-[24px]">Discover</h1><div class="mt-4 grid grid-cols-2 md:grid-cols-4 gap-3">${Array.from({length:8}).map((_,i)=>`<div class="phone h-[220px] relative"><img src="https://randomuser.me/api/portraits/${i%2?'women':'men'}/${10+i}.jpg" class="w-full h-full object-cover"/><div class="absolute bottom-0 w-full p-2 bg-gradient-to-t from-black/80 to-transparent text-white"><div class="font-bold text-[11px]">User ${i+1}, ${22+i}</div></div></div>`).join('')}</div></div>`}
