export function onboarding(step=1){
const S=[
`<div class="text-center pt-6"><div class="text-[56px]">💬</div><h1 class="text-[24px] font-black mt-4">Welcome to<br/>KLA-MEET</h1><button onclick="location.href='/signup/?step=2'" class="mt-10 w-full bg-[#FFC700] py-3.5 rounded-full font-black border-2 border-black">Get Started</button></div>`,
`<div><div class="text-[11px] font-bold">Step 1 of 5 - 20%</div><h2 class="font-black text-[18px] mt-4">Create your profile</h2><input placeholder="Name" class="w-full border-2 border-black rounded-xl p-3 mt-4"/><button onclick="location.href='/signup/?step=3'" class="mt-6 w-full bg-[#FFC700] py-3.5 rounded-full font-black border-2 border-black">Continue</button></div>`,
`<div><div class="text-[11px] font-bold">Step 2 of 5 - 40%</div><h2 class="font-black text-[18px] mt-4">Gender</h2><button onclick="location.href='/signup/?step=4'" class="mt-6 w-full bg-[#FFC700] py-3.5 rounded-full font-black border-2 border-black">Continue</button></div>`,
`<div><h2 class="font-black text-[18px]">Interests</h2><div class="grid grid-cols-2 gap-2 mt-4 text-[12px] font-bold"><div class="border-2 border-black rounded-full py-2 text-center bg-[#FFC700]">Music</div><div class="border-2 border-black rounded-full py-2 text-center">Travel</div><div class="border-2 border-black rounded-full py-2 text-center">Foodie</div><div class="border-2 border-black rounded-full py-2 text-center">Fitness</div></div><button onclick="location.href='/signup/?step=5'" class="mt-6 w-full bg-[#FFC700] py-3.5 rounded-full font-black border-2 border-black">Continue</button></div>`,
`<div class="text-center"><h2 class="font-black text-[20px]">Enable location &<br/>Find matches near you</h2><div class="my-10 text-[64px]">📍</div><button onclick="location.href='/'" class="mt-8 w-full bg-[#FFC700] py-3.5 rounded-full font-black border-2 border-black">Allow Location</button></div>`
];
return `<div class="min-h-screen bg-zinc-100 grid place-items-center p-6"><div class="bg-white w-[360px] min-h-[580px] rounded-[32px] p-7 border-[3px] border-black flex flex-col">${S[step-1]}<div class="mt-auto flex justify-center gap-1 pt-6">${[1,2,3,4,5].map(i=>`<div class="w-2 h-2 rounded-full ${i===step?'bg-[#FFC700] w-6':'bg-zinc-300'}"></div>`).join('')}</div></div></div>`
}
