export function onboarding(step=1){
const steps=[
`<div class="text-center"><div class="text-5xl mb-6">💬</div><h1 class="text-2xl font-black">Welcome to KLA-MEET</h1><p class="text-zinc-500 text-sm mt-1">Date. Meet. Connect. Worldwide.</p><button onclick="location.href='/signup/?step=2'" class="mt-8 w-full bg-[#FFC700] py-3 rounded-full font-black border-2 border-black">Get Started</button></div>`,
`<div><h1 class="text-xl font-black text-center">Create your profile</h1><p class="font-bold mt-6 text-sm">Let's get to know you</p><input placeholder="Enter your name" class="w-full border-2 border-black rounded-xl p-3 mt-2"/><input placeholder="DD/MM/YYYY" class="w-full border-2 border-black rounded-xl p-3 mt-3"/><button onclick="location.href='/signup/?step=3'" class="mt-4 w-full bg-[#FFC700] py-3 rounded-full font-black border-2 border-black">Continue</button></div>`,
`<div><h1 class="font-black">Gender & Preferences</h1><div class="mt-4 space-y-3"><label class="flex justify-between border-2 border-black rounded-xl p-3"><span>Woman</span><input type="radio" name="g" checked/></label><label class="flex justify-between border-2 border-black rounded-xl p-3"><span>Man</span><input type="radio" name="g"/></label><label class="flex justify-between border-2 border-black rounded-xl p-3"><span>Nonbinary</span><input type="radio" name="g"/></label></div><button onclick="location.href='/signup/?step=4'" class="mt-4 w-full bg-[#FFC700] py-3 rounded-full font-black">Continue</button></div>`,
`<div><h1 class="font-black text-xl">What are you into?</h1><div class="grid grid-cols-2 gap-2 mt-4 text-sm">${['Music','Travel','Foodie','Fitness','Arts','Photo','Reading','Outdoors'].map(i=>`<div class="border-2 border-black rounded-full py-2 px-3 font-bold text-center">${i}</div>`).join('')}</div><button onclick="location.href='/signup/?step=5'" class="mt-4 w-full bg-[#FFC700] py-3 rounded-full font-black">Continue</button></div>`,
`<div><h1 class="font-black text-center">Enable location & Find matches near you</h1><div class="text-6xl text-center my-6">📍</div><button onclick="location.href='/discover/'" class="mt-4 w-full bg-[#FFC700] py-3 rounded-full font-black">Allow Location</button><button onclick="location.href='/discover/'" class="w-full text-center text-xs mt-3 font-bold">Maybe later</button></div>`
];
return `<div class="min-h-screen bg-zinc-100 grid place-items-center p-6"><div class="bg-white w-[340px] rounded-[32px] p-6 border-2 border-black kla-shadow">${steps[step-1]||steps[0]}<div class="flex justify-center gap-1 mt-6">${[1,2,3,4,5].map(i=>`<div class="w-1.5 h-1.5 rounded-full ${i===step?'bg-[#FFC700]':'bg-zinc-300'}"></div>`).join('')}</div></div></div>`
}
