'use client';






import { useRef, useState } from 'react'
import Link from 'next/link'
import BottomNav from '@/components/BottomNav'
import { supabase } from '@/lib/supabase'

type DocType = 'National ID' | 'Passport' | 'Driving Licence'

export default function VerificationPage() {
  const frontInput = useRef<HTMLInputElement>(null); const backInput = useRef<HTMLInputElement>(null); const selfieInput = useRef<HTMLInputElement>(null)
  const [docType, setDocType] = useState<DocType>('National ID'); const [front, setFront] = useState<File | null>(null); const [back, setBack] = useState<File | null>(null); const [selfie, setSelfie] = useState<File | null>(null); const [state, setState] = useState(''); const [busy, setBusy] = useState(false)
  const choose = (setter: (file: File | null) => void, input: React.ChangeEvent<HTMLInputElement>) => { const file = input.target.files?.[0] || null; if (file && (!file.type.startsWith('image/') || file.size > 5 * 1024 * 1024)) setState('Use an image smaller than 5MB.'); else setter(file); input.currentTarget.value = '' }
  const upload = async (file: File, userId: string, label: string) => { const path = `${userId}/${Date.now()}-${label}.jpg`; const { error } = await supabase.storage.from('verifications').upload(path, file, { contentType: file.type, upsert: false }); if (error) throw error; return path }
  const verify = async () => { if (!front || !back || !selfie) return setState('Upload the front, back and a live selfie first.'); setBusy(true); setState('Checking...'); try { const { data: session } = await supabase.auth.getSession(); const userId = session.session?.user.id; const token = session.session?.access_token; if (!userId || !token) throw new Error('Sign in to verify your profile.'); const [docFrontPath, docBackPath, selfiePath] = await Promise.all([upload(front, userId, 'front'), upload(back, userId, 'back'), upload(selfie, userId, 'selfie')]); await supabase.from('profiles').update({ verification_status: 'pending_auto_verified', id_type: docType }).eq('id', userId); await new Promise(resolve => window.setTimeout(resolve, 3000)); const response = await fetch('/api/verify', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ docType, docFrontPath, docBackPath, selfiePath }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || 'Automatic verification failed.'); setState('Verified ✅'); } catch (error) { setState(error instanceof Error ? error.message : 'Verification failed') } finally { setBusy(false) } }
  return <div className="app-shell"><header className="topbar"><Link href="/profile" className="icon-button" aria-label="Back to profile">←</Link><div><p className="eyebrow">Automatic verification</p><h1 className="display text-2xl font-bold mt-1">Get your blue tick</h1></div><div className="w-10 h-10 rounded-full bg-sky-100 grid place-items-center font-bold text-sky-600">✓</div></header><main className="content animate-page"><section className="soft-panel mt-4"><p className="text-sm text-stone-500">Verified by ID, Passport or Driving Licence. Your documents stay private and only the verified badge is shown publicly.</p><div className="mt-5 grid grid-cols-3 gap-2">{(['National ID', 'Passport', 'Driving Licence'] as DocType[]).map(type => <button key={type} type="button" onClick={() => setDocType(type)} className={`rounded-2xl border p-3 text-xs font-bold ${docType === type ? 'border-[#ffc800] bg-[#ffc800] text-[#202020]' : 'border-[#e5e5e5] bg-white'}`}>{type}</button>)}</div><div className="mt-6 space-y-3"><input ref={frontInput} className="hidden" type="file" accept="image/*" capture="environment" onChange={event => choose(setFront, event)} /><input ref={backInput} className="hidden" type="file" accept="image/*" capture="environment" onChange={event => choose(setBack, event)} /><input ref={selfieInput} className="hidden" type="file" accept="image/*" capture="user" onChange={event => choose(setSelfie, event)} /><button type="button" disabled={busy} onClick={() => frontInput.current?.click()} className="field text-left font-bold">1. {front ? `Front uploaded: ${front.name}` : 'Upload document front'}</button><button type="button" disabled={busy} onClick={() => backInput.current?.click()} className="field text-left font-bold">2. {back ? `Back uploaded: ${back.name}` : 'Upload document back'}</button><button type="button" disabled={busy} onClick={() => selfieInput.current?.click()} className="field text-left font-bold">3. {selfie ? `Live selfie ready: ${selfie.name}` : 'Take live selfie'}</button><button type="button" disabled={busy} onClick={verify} className="primary-button w-full">{busy ? 'Checking...' : '4. Verify automatically'}</button>{state && <p role="status" className={`text-center text-sm font-bold ${state === 'Verified ✅' ? 'text-sky-600' : 'text-stone-500'}`}>{state}</p>}</div></section></main><BottomNav /></div>
}
